
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://kirkclemons.tk"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: "UA-102482306-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Kirk Clemons"
title: "Kirk Clemons"
description: "Kirk Clemons"
keywords: "web, developer, frontend, design, graphics, freelance, hire, responsive,"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/mug-bw.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: False
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "Website Setup // Design // Development<br>HTML // CSS // JavaScript // PHP<br>3D Rendering // Printable Media // Graphics"

# me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/kcclemo.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: false

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

# disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/slto-logo.jpg"
    date: ""
    description: "<a href='./seelemonsthinkoils/'>See Lemons Think Oils</a>"
    link: "./seelemonsthinkoils/"
  - image: "/img/timeline/panhandle-logworks-156.png"
    date: ""
    description: "<a href='./panhandlelogworks/'>Panhandle Logworks</a>"
    link: "./panhandlelogworks/"
  - image: "/img/timeline/cabin-fever-crafts.jpg"
    date: ""
    description: "<a href='./cabinfevercrafts/'>Cabin Fever Crafts</a>"
    link: "./cabinfevercrafts/"
  - image: "/img/timeline/joel-clark-knives.png"
    date: ""
    description: "<a href='./joelclarkknives/'>Joel Clark Custom Knives</a>"
    link: "./joelclarkknives/"
  - image: "/img/timeline/northstar_logo_blk.png"
    date: ""
    description: "<a href='./northstarbaptistchurch/'>NorthStar Baptist Church</a>"
    link: "./northstarbaptistchurch/"

# First image of the Timeline

timeline-img: "/img/timeline/mug.jpg"

###########
# Contact #
###########

email: "kirk.clemons@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Kirk Clemons is a front end web developer and digital artist located in beautiful Coeur d'Alene, Idaho. Kirk loves to spend time with his wife and three kids, write code, and make things."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
# title should equal the font awesome icon name you want to use.
  - title: "linkedin"
    url: "https://www.linkedin.com/in/kirkclemons/"

  - title: "github"
    url: "https://github.com/kcclemo"

  - title: "codepen"
    url: "https://codepen.io/kcclemo/"

  - title: "deviantart"
    url: "https://www.deviantart.com/kcclemo"

############
# 404 page #
############

err-404-img: "/img/favicon.ico"

##################
# GPG on Keybase #
##################

keybase-username: kcclemo
keybase-in-social: False
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  # Blog: 'latest-post'
  Experience: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

#paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
